In [1]:
import numpy as np
import sys
sys.path.append(r"../Communiaction")
sys.path.append(r"../Utils")
sys.path.append(r"../../NeuralNetworks/Utils")
import NN_Utils
import TCP_IP_UTILS
import Utils
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
import torch
import torch.nn as nn

In [2]:
On_Chip = False
if On_Chip:
    HOST = '192.168.1.10'  # Remote device IP (server IP)
    PORT = 7               # Echo port
    client_socket = TCP_IP_UTILS.tcp_connect(HOST,PORT)
    ret_data = Utils.Set_ChipIO_to_Default(client_socket)
    print(ret_data)
else:
    client_socket = None

In [2]:
x = torch.tensor([[1.1234, 2.344, 3.56],
                  [4.0, 5.0, 6.0]]).to("cuda")

# Define Linear layer: 3 input features → 2 output features, no bias
linear = nn.Linear(in_features=3, out_features=2, bias=False)

# Manually set weights for clarity (optional)
# Shape of weight: (out_features, in_features)
linear.weight.data = torch.tensor([[1.0, 0.0, -1.0],
                                   [0.5, 0.5, 0.5]]).to("cuda")

In [3]:
# Apply linear layer
output = linear(x)

# Print result
print("Output:\n", output)

Output:
 tensor([[-2.4366,  3.5137],
        [-2.0000,  7.5000]], device='cuda:0', grad_fn=<MmBackward0>)


In [16]:
TD_DEL_LUT_PATH = r"d:\Chip2025\Chip2025_Testing\NeuralNetworks\Utils\Hardware_Model\HW_MODEL_TD_DEL.npy"
TD_LUT_PATH = r"d:\Chip2025\Chip2025_Testing\NeuralNetworks\Utils\Hardware_Model\HW_MODEL_TD_1x_Ref256.npy"
CD_LUT_PATH = r"d:\Chip2025\Chip2025_Testing\NeuralNetworks\Utils\Hardware_Model\HW_MODEL_CD_4x_Ref256_sweep4.npy"
LUT_PATHS = [TD_LUT_PATH,CD_LUT_PATH]
LUT_FLAGS = [False,True,False]


In [17]:
Lin1 = NN_Utils.Linear(1,x,linear.weight.data,[8,10],None,client_socket,LUT_FLAGS,LUT_PATHS)
out,sum = Lin1.linear_onChip()
print("Output:\n", out)

Output:
 tensor([[9.7656e-04, 3.9692e+00],
        [1.9531e-03, 7.0010e+00]])


In [18]:
TD_DEL_LUT_PATH = r"d:\Chip2025\Chip2025_Testing\NeuralNetworks\Utils\Hardware_Model\HW_MODEL_TD_DEL.npy"
TD_LUT_PATH = r"d:\Chip2025\Chip2025_Testing\Python_Notebook\Tests\Data\Hardware_Model\HW_MODEL_TD_1x_FastIMC.npy"
CD_LUT_PATH = r"d:\Chip2025\Chip2025_Testing\NeuralNetworks\Utils\Hardware_Model\HW_MODEL_CD_4x_Ref256_sweep4.npy"
LUT_PATHS = [TD_LUT_PATH,CD_LUT_PATH]
LUT_FLAGS = [False,True,False]

In [19]:
Lin1 = NN_Utils.Linear(1,x,linear.weight.data,[8,10],None,client_socket,LUT_FLAGS,LUT_PATHS)
out,sum = Lin1.linear_onChip()
print("Output:\n", out)

Output:
 tensor([[0.2820, 3.3598],
        [5.0015, 7.7509]])
